verb =  [
"Accelerating ",
"Achieving ",
"Addressing ",
"Bridging ",
"Bringing ",
"Building ",
"Boosting ",
"Capacitating ",
"Catalyzing ",
"Developing ",
"Diversifying ",
"Empowering ",
"Encouraging ",
"Engaging ",
"Enhancing ",
"Establishing ",
"Evaluating ",
"Facilitating ",
"Financing ",
"Focusing ",
"Fostering ",
"Greening ",
"Growing ",
"Harmonizing ",
"Implementing ",
"Improving ",
"Institutionalizing ",
"Investing in ",
"Leveling the Playing Field for ",
"Leveraging ",
"Liberalizing ",
"Linking ",
"Mainstreaming ",
"Making ",
"Maximizing ",
"Modernizing ",
"Monitoring ",
"Operationalizing ",
"Partnering ",
"Prioritizing ",
"Producing ",
"Promoting ",
"Promoting Innovation on ",
"Providing ",
"Raising ",
"Realizing ",
"Rebuilding ",
"Reforming ",
"Restructuring ",
"Revitalizing ",
"Steering ",
"Streamlining ",
"Strengthening ",
"Supporting ",
"Sustaining ",
"Tracking ",
"Transforming ",
"Utilizing ",
"Workshop on ",
]

modifier =  [
"Aid ",
"Appropriate ",
"Coherent ",
"Community-Driven ",
"Core ",
"Cost-Effective ",
"Country-Led ",
"Cross-Regional ",
"Cross-Cutting ",
"Decent ",
"Digital ",
"E-Government ",
"Economic ",
"Ecotourism ",
"Effective ",
"Efficient ",
"Emerging ",
"Empowered ",
"Energy Generation ",
"Equitable ",
"Fiscal ",
"Food ",
"Forest ",
"Fisheries ",
"Global ",
"ICT4D ",
"Inclusive ",
"Indigenous ",
"Industrial ",
"Innovative ",
"Institutional ",
"Integrated ",
"Inter-Agency ",
"Intergovernmental ",
"Irrigation ",
"Job ",
"Key ",
"Labor ",
"Local ",
"Market-Oriented ",
"Microfinance ",
"Multi-Sectoral ",
"National ",
"Open Data ",
"Participatory ",
"Peace and Justice ",
"Post-2015 ",
"Post-2020 ",
"Post-Conflict ",
"Post-Disaster ",
"Primary Health Care ",
"Pro-Poor ",
"Public ",
"Public-Private ",
"Regional ",
"Regulatory ",
"Responsible ",
"Space Force ",
"Strategic ",
"Social Protection ",
"South-South ",
"Sub-National ",
"Sustainable ",
"Telecommunication ",
"Tourism ",
"Transparent ",
"Water "
]

noun =  [
"Access ",
"Accountability ",
"Activities ",
"Administration ",
"Approaches ",
"Assessment ",
"Assistance ",
"Best Practices ",
"Capability ",
"Capacity ",
"Collaboration ",
"Committment ",
"Communication and Outreach ",
"Competitiveness ",
"Conditional Cash Transfers ",
"Consumption and Production ",
"Cooperation ",
"Development ",
"Development Framework ",
"Dialogue ",
"Diversity ",
"Economies ",
"Effectiveness ",
"Efficiency ",
"Enterprise ",
"Equality ",
"Extension and Research ",
"Financing for Development ",
"Goals ",
"Governance ",
"Growth ",
"Impact ",
"Inclusion ",
"Inclusivity ",
"Indicators ",
"Income-Generation ",
"Industries ",
"Innovation ",
"Institutions ",
"Integration ",
"Interventions ",
"Involvement ",
"Knowledge, Skills and Practices ",
"Knowledge Management ",
"Lending ",
"Linkages ",
"Liberalization ",
"Livelihoods ",
"Management ",
"Markets ",
"Mechanisms ",
"Monitoring and Evaluation ",
"Opportunities ",
"Outcomes ",
"Participation ",
"Partners ",
"Partnerships ",
"Performance ",
"Planning ",
"Plans ",
"Platforms ",
"Policies ",
"Policy Framework ",
"Portfolio ",
"Priorities ",
"Privatization ",
"Processes ",
"Production ",
"Programs ",
"Progress ",
"Prosperity ",
"Recovery ",
"Reforms ",
"Resources ",
"Responsiveness ",
"Results ",
"Sanitation ",
"Security ",
"Services ",
"Stability ",
"Stakeholders ",
"Strategies ",
"Sustainability ",
"Targets ",
"Technologies ",
"Transparency "
]

object = [
"for Direct Target Beneficiaries",
"for Indigenous People",
"for Fisherfolks",
"for Local Policymakers and Practitioners",
"for Poor People",
"for Small-Holder Farmers",
"for State-Owned Enterprises",
"for the Global Commons",
"for the Poorest of the Poor",
"for the World Economy",
"in a Volatile World",
"in Arid Regions",
"in Biodiversity Hotspots ",
"in Civil Society Organizations",
"in Client Countries",
"in Developing Countries",
"in Emerging Economies",
"in Emerging Markets",
"in Far-Flung Communities",
"in Fishing Communities",
"in Fragile and Failed States",
"in Frontier Markets",
"in Growing Economies",
"in Highly-Urbanized Areas",
"in Indigenous Communities",
"in Industrializing Nations",
"in Land-Locked Countries",
"in Least Developed Countries",
"in Less Developed Countries",
"in Less Economically Developed Countries",
"in Low- and Middle-Income Countries",
"in Low-Income Households",
"in Low-Lying Communities",
"in Marginalized Communities",
"in Member-States",
"in Middle-Income Countries",
"in MNCs, INGOs, and BINGOs",
"in Newly-Industrialized Countries",
"in Off-Grid Villages",
"in Pastoral Communities",
"in Poor Nations",
"in Protected Areas",
"in Remote Communities",
"in Remote Villages",
"in Rural Communes ",
"in Rurban Areas ",
"in Semi-Arid Regions ",
"in Small Island Developing States",
"in Sustainable Cities",
"in the Business Sector",
"in the Developing World",
"in the Global South",
"in the Last Frontier of the World",
"in the Local Government",
"in the Poorest Countries",
"in the Private Sector",
"in Transboundary Trade Corridors",
"in Transnational Borders",
"in Tropical Forests",
"in Underdeveloped Countries",
"in Upland Areas",
"in Vulnerable Nations",
"in Vulnerable Populations",
]

function newTitle() {
  randverb = verb[Math.floor(Math.random() * verb.length)];
  randmodifier = modifier[Math.floor(Math.random() * modifier.length)];
  randnoun = noun[Math.floor(Math.random() * noun.length)];
  randobject = object[Math.floor(Math.random() * object.length)];
  projectTitle = "\"" + randverb + randmodifier + randnoun + randobject + "\"";
  document.getElementById("project-title").innerHTML = projectTitle;
}
